theme: jekyll-theme-cayman
google_analytics: "UA-158624413-1"

title: Latin Sindhi
description: A new script for Sindhi Language!

content: "In Sindh, Pakistan the Sindhi language is written in modified persio-Arabic script and in India it is written in Devanagari (Hindi) Script."
